export const ADMIN_LOG_CREATE_REQUEST = 'ADMIN_LOG_CREATE_REQUEST';
export const ADMIN_LOG_CREATE_SUCCESS = 'ADMIN_LOG_CREATE_SUCCESS';
export const ADMIN_LOG_CREATE_FAIL = 'ADMIN_LOG_CREATE_FAIL';
export const ADMIN_LOG_CREATE_RESET = 'ADMIN_LOG_CREATE_RESET';
