export const TEST_CREATE_REQUEST = 'TEST_CREATE_REQUEST';
export const TEST_CREATE_SUCCESS = 'TEST_CREATE_SUCCESS';
export const TEST_CREATE_FAIL = 'TEST_CREATE_FAIL';
export const TEST_CREATE_RESET = 'TEST_CREATE_RESET';

export const TEST_LIST_REQUEST = 'TEST_LIST_REQUEST';
export const TEST_LIST_SUCCESS = 'TEST_LIST_SUCCESS';
export const TEST_LIST_FAIL = 'TEST_LIST_FAIL';
export const TEST_LIST_RESET = 'TEST_LIST_RESET';

export const TEST_UPDATE_REQUEST = 'TEST_UPDATE_REQUEST';
export const TEST_UPDATE_SUCCESS = 'TEST_UPDATE_SUCCESS';
export const TEST_UPDATE_FAIL = 'TEST_UPDATE_FAIL';
export const TEST_UPDATE_RESET = 'TEST_UPDATE_RESET';

export const TEST_LIST_ADMIN_REQUEST = 'TEST_LIST_ADMIN_REQUEST';
export const TEST_LIST_ADMIN_SUCCESS = 'TEST_LIST_ADMIN_SUCCESS';
export const TEST_LIST_ADMIN_FAIL = 'TEST_LIST_ADMIN_FAIL';
export const TEST_LIST_ADMIN_RESET = 'TEST_LIST_ADMIN_RESET';

export const TEST_PATIENT_PDF_REQUEST = 'TEST_PATIENT_PDF_REQUEST';
export const TEST_PATIENT_PDF_SUCCESS = 'TEST_PATIENT_PDF_SUCCESS';
export const TEST_PATIENT_PDF_FAIL = 'TEST_PATIENT_PDF_FAIL';
export const TEST_PATIENT_PDF_RESET = 'TEST_PATIENT_PDF_RESET';

export const TEST_DSP_CSV_REQUEST = 'TEST_DSP_CSV_REQUEST';
export const TEST_DSP_CSV_SUCCESS = 'TEST_DSP_CSV_SUCCESS';
export const TEST_DSP_CSV_FAIL = 'TEST_DSP_CSV_FAIL';
export const TEST_DSP_CSV_RESET = 'TEST_DSP_CSV_RESET';
export const TEST_DSP_CSV_RESET_SUCCESS = 'TEST_DSP_CSV_RESET_SUCCESS';

export const TEST_VERIFY_REQUEST = 'TEST_VERIFY_REQUEST';
export const TEST_VERIFY_SUCCESS = 'TEST_VERIFY_SUCCESS';
export const TEST_VERIFY_FAIL = 'TEST_VERIFY_FAIL';
export const TEST_VERIFY_RESET = 'TEST_VERIFY_RESET';

export const TEST_DOWNLOAD_PDF_REQUEST = 'TEST_DOWNLOAD_PDF_REQUEST';
export const TEST_DOWNLOAD_PDF_SUCCESS = 'TEST_DOWNLOAD_PDF_SUCCESS';
export const TEST_DOWNLOAD_PDF_FAIL = 'TEST_DOWNLOAD_PDF_FAIL';
export const TEST_DOWNLOAD_PDF_RESET = 'TEST_DOWNLOAD_PDF_RESET';

export const TEST_EDIT_REQUEST = 'TEST_EDIT_REQUEST';
export const TEST_EDIT_SUCCESS = 'TEST_EDIT_SUCCESS';
export const TEST_EDIT_FAIL = 'TEST_EDIT_FAIL';
export const TEST_EDIT_RESET = 'TEST_EDIT_RESET';
