export const TEST_CREATE_REQUEST = 'TEST_CREATE_REQUEST';
export const TEST_CREATE_SUCCESS = 'TEST_CREATE_SUCCESS';
export const TEST_CREATE_FAIL = 'TEST_CREATE_FAIL';
export const TEST_CREATE_RESET = 'TEST_CREATE_RESET';

export const TEST_LIST_REQUEST = 'TEST_LIST_REQUEST';
export const TEST_LIST_SUCCESS = 'TEST_LIST_SUCCESS';
export const TEST_LIST_FAIL = 'TEST_LIST_FAIL';
export const TEST_LIST_RESET = 'TEST_LIST_RESET';

export const TEST_UPDATE_REQUEST = 'TEST_UPDATE_REQUEST';
export const TEST_UPDATE_SUCCESS = 'TEST_UPDATE_SUCCESS';
export const TEST_UPDATE_FAIL = 'TEST_UPDATE_FAIL';
export const TEST_UPDATE_RESET = 'TEST_UPDATE_RESET';

export const TEST_LIST_ADMIN_REQUEST = 'TEST_LIST_ADMIN_REQUEST';
export const TEST_LIST_ADMIN_SUCCESS = 'TEST_LIST_ADMIN_SUCCESS';
export const TEST_LIST_ADMIN_FAIL = 'TEST_LIST_ADMIN_FAIL';
export const TEST_LIST_ADMIN_RESET = 'TEST_LIST_ADMIN_RESET';
